up

diff --git a/.bin/kill-selenium b/.bin/kill-selenium
--- a/.bin/kill-selenium
+++ b/.bin/kill-selenium
@@ -27,4 +27,12 @@ done
 echo -e "Containers running: $CONTAINER_COUNT\ntests have finished! stopping selenium..."
 docker stop $(docker ps -q)
 
+# determine if there were failures
+FAIL_FILE="./dev/tests/acceptance/tests/_output/failed"
+if [ -f $FAIL_FILE ]; then
+    echo "there were failed tests!"
+    cat $FAIL_FILE
+    exit 1
+fi
 
+exit 0
