test

diff --git a/.bin/kill-selenium b/.bin/kill-selenium
--- a/.bin/kill-selenium
+++ b/.bin/kill-selenium
@@ -26,12 +26,14 @@ done
 echo -e "Containers running: $CONTAINER_COUNT\ntests have finished! stopping selenium..."
 docker stop $(docker ps -q)
 
-# determine if there were failures 
+# determine if there were failures
 FAIL_FILE="./dev/tests/acceptance/tests/_output/failed"
 if [ -f $FAIL_FILE ]; then
     echo "there were failed tests!"
     cat $FAIL_FILE
     exit 1
+    exit 246
+    exit 257
 fi
 
 exit 0
